/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Database.databaseManager;
import beanClasses.customerBean;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class customerFrame extends javax.swing.JFrame {

    /**
     * Creates new form customerFrame
     */
    public customerFrame() {
        initComponents();
        getCustomer();
    }
    private void getCustomer(){
      
    try{
        Vector v=databaseManager.getCustomer();
        customerL.setListData(v);
    }catch(Exception e){
        e.printStackTrace ();
      JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
    
    }       
    }
    
    private void addRecord(){
    String firstName =firstNameTF.getText() ;
    String lastName= lastNameTF.getText();
    String city= cityTF.getText();
    String country = countryTF.getText();
    String state = stateTF.getText();
    String address = addressTF.getText();
    int contactNo =Integer.parseInt(contactNoTF.getText());
    String email= emailTF.getText();
    //java.util.Date dateOfCreate=dateOfCreateTF.getText();
    String date1 = dateOfCreateTF.getText();
    String remarks=remarksTA.getText();
    try{
        int rows=databaseManager.addCutomer(firstName,lastName,city,country,state,address,contactNo,email,date1,remarks);
                if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+"Record Insert ");
                
                getCustomer();

          }catch(Exception e){
                //   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
    }
    
    private void clear(){
    firstNameTF.setText("") ;
    lastNameTF.setText("");
    cityTF.setText("");
    countryTF.setText("");
    stateTF.setText("");
    addressTF.setText("");
    contactNoTF.setText("");
    emailTF.setText("");
    dateOfCreateTF.setText("");
    remarksTA.setText("");
    }
    private void updateRecord(){
    String firstName =firstNameTF.getText() ;
    String lastName= lastNameTF.getText();
    String city= cityTF.getText();
    String country = countryTF.getText();
    String state = stateTF.getText();
    String address = addressTF.getText();
    int contactNo =Integer.parseInt(contactNoTF.getText());
    String email= emailTF.getText();
    String dateOfCreate= dateOfCreateTF.getText();
    String remarks=remarksTA.getText();
  
        customerBean bean = (customerBean)customerL.getSelectedValue();
        if(bean==null)return;
        try{
        int rows=databaseManager.updateCustomer(bean.getCutomerId(), firstName, lastName, city, state, country, address, email, contactNo, dateOfCreate, remarks);
          if(rows>=1)
                    JOptionPane.showMessageDialog(this, rows+"Record Insert ");
                clear();
                getCustomer();
            }catch(Exception e){
                   JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                   e.printStackTrace();
            }
    }
    
    private void deleteRecord(){
    customerBean bean = (customerBean)customerL.getSelectedValue();
    if(bean==null)return;
    try{
        int rows = databaseManager.deleteCustomer(bean.getCutomerId());
          if(rows>=1)
              JOptionPane.showMessageDialog(this, rows+" Delete ");
                clear();
                getCustomer();
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
                e.printStackTrace();
            }
         } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        dateOfCreateTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        addressTF = new javax.swing.JTextField();
        countryTF = new javax.swing.JTextField();
        stateTF = new javax.swing.JTextField();
        cityTF = new javax.swing.JTextField();
        lastNameTF = new javax.swing.JTextField();
        firstNameTF = new javax.swing.JTextField();
        customerIdTF = new javax.swing.JTextField();
        contactNoTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerL = new javax.swing.JList();
        clearB = new javax.swing.JButton();
        deleteB = new javax.swing.JButton();
        backB = new javax.swing.JButton();
        updateB = new javax.swing.JButton();
        addB = new javax.swing.JButton();
        nicTF = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("customer");
        setMinimumSize(new java.awt.Dimension(794, 740));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("STATE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 290, 90, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("CITY");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 240, 80, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("LAST NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 190, 90, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("FIRST NAME");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(120, 140, 80, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("CUSTOMER ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 90, 90, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("COUNTRY");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(120, 340, 100, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("ADDRESS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(120, 390, 90, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("EMAIL");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(120, 440, 90, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("DATE OF CREATE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 90, 100, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("CONTACT NO");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(120, 490, 90, 40);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("REMARKS");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(130, 580, 70, 14);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("CUSTOMER lIST");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(580, 60, 120, 30);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("CUSTOMER");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 20, 130, 14);

        dateOfCreateTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(dateOfCreateTF);
        dateOfCreateTF.setBounds(430, 90, 130, 40);

        emailTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(emailTF);
        emailTF.setBounds(210, 440, 360, 40);

        addressTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(addressTF);
        addressTF.setBounds(210, 390, 360, 40);

        countryTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        countryTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryTFActionPerformed(evt);
            }
        });
        getContentPane().add(countryTF);
        countryTF.setBounds(210, 340, 360, 40);

        stateTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        stateTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTFActionPerformed(evt);
            }
        });
        getContentPane().add(stateTF);
        stateTF.setBounds(210, 290, 360, 40);

        cityTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(cityTF);
        cityTF.setBounds(210, 240, 360, 40);

        lastNameTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(lastNameTF);
        lastNameTF.setBounds(210, 190, 360, 40);

        firstNameTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(firstNameTF);
        firstNameTF.setBounds(210, 140, 360, 40);

        customerIdTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerIdTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdTFActionPerformed(evt);
            }
        });
        getContentPane().add(customerIdTF);
        customerIdTF.setBounds(210, 90, 110, 40);

        contactNoTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(contactNoTF);
        contactNoTF.setBounds(210, 490, 130, 40);

        remarksTA.setColumns(20);
        remarksTA.setRows(5);
        remarksTA.setText("\n");
        jScrollPane1.setViewportView(remarksTA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 580, 560, 70);

        customerL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerL.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                customerLValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(customerL);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(580, 90, 190, 480);

        clearB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        clearB.setText("CLEARE");
        clearB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBActionPerformed(evt);
            }
        });
        getContentPane().add(clearB);
        clearB.setBounds(460, 660, 80, 30);

        deleteB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        deleteB.setText("DELETE");
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });
        getContentPane().add(deleteB);
        deleteB.setBounds(590, 660, 80, 30);

        backB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        backB.setText("BACK");
        backB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBMouseClicked(evt);
            }
        });
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        getContentPane().add(backB);
        backB.setBounds(700, 660, 70, 30);

        updateB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        updateB.setText("UPDATE");
        updateB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBActionPerformed(evt);
            }
        });
        getContentPane().add(updateB);
        updateB.setBounds(350, 660, 79, 30);

        addB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        addB.setText("ADD");
        addB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBActionPerformed(evt);
            }
        });
        getContentPane().add(addB);
        addB.setBounds(220, 660, 70, 30);

        nicTF.setText("jTextField1");
        getContentPane().add(nicTF);
        nicTF.setBounds(210, 540, 360, 30);

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("NIC");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(140, 540, 70, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stateTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTFActionPerformed

    private void countryTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryTFActionPerformed

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
    hide();
    }//GEN-LAST:event_backBActionPerformed

    private void customerIdTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdTFActionPerformed

    private void customerLValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_customerLValueChanged
customerBean bean=(customerBean)customerL.getSelectedValue();
        if(bean==null)return;
        java.text.SimpleDateFormat f = new java.text.SimpleDateFormat("dd-MMM-yyyy");
             String d="";
             if(bean.getDateOfCreate()!=null)
                d=f.format(bean.getDateOfCreate());
        customerIdTF.setText(""+bean.getCutomerId());
        firstNameTF.setText(bean.getFirstName());
        lastNameTF.setText(bean.getLastName());
        emailTF.setText(bean.getEmail());
        countryTF.setText(bean.getCountry());
        cityTF.setText(bean.getCity());
        addressTF.setText(bean.getAdress());
        stateTF.setText(bean.getState());
        contactNoTF.setText(""+bean.getCntactNo());
        dateOfCreateTF.setText(d);
        nicTF.setText(""+bean.getCnic());
        remarksTA.setText(bean.getRemrks());
        
   
    }//GEN-LAST:event_customerLValueChanged

    private void addBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBActionPerformed
        addRecord();
    }//GEN-LAST:event_addBActionPerformed

    private void clearBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBActionPerformed
        clear();
    }//GEN-LAST:event_clearBActionPerformed

    private void deleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBActionPerformed
        // TODO add your handling code here:
        deleteRecord();
    }//GEN-LAST:event_deleteBActionPerformed

    private void updateBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBActionPerformed
        // TODO add your handling code here:
        updateRecord();
    }//GEN-LAST:event_updateBActionPerformed

    private void backBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBMouseClicked
     Bank ob = new Bank();
     ob.setVisible(true);
     dispose();
        
    }//GEN-LAST:event_backBMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addB;
    private javax.swing.JTextField addressTF;
    private javax.swing.JButton backB;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cityTF;
    private javax.swing.JButton clearB;
    private javax.swing.JTextField contactNoTF;
    private javax.swing.JTextField countryTF;
    private javax.swing.JTextField customerIdTF;
    private javax.swing.JList customerL;
    private javax.swing.JTextField dateOfCreateTF;
    private javax.swing.JButton deleteB;
    private javax.swing.JTextField emailTF;
    private javax.swing.JTextField firstNameTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameTF;
    private javax.swing.JTextField nicTF;
    private javax.swing.JTextArea remarksTA;
    private javax.swing.JTextField stateTF;
    private javax.swing.JButton updateB;
    // End of variables declaration//GEN-END:variables
}
