/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Database.databaseManager;
import beanClasses.accountBean;
import beanClasses.customerBean;
import beanClasses.transactionBean;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class dpositFrame extends javax.swing.JFrame {

    /**
     * Creates new form dpositFrame
     */
    public dpositFrame() {
        initComponents();
        getCustomer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        accountC = new javax.swing.JComboBox();
        customerC = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        dateOfTransactionTF = new javax.swing.JTextField();
        doneB = new javax.swing.JButton();
        backB = new javax.swing.JButton();
        amountTypeTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 640));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("ACCOUNT ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 170, 90, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("CUSTOMER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 110, 90, 40);

        accountC.setEditable(true);
        accountC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(accountC);
        accountC.setBounds(240, 170, 300, 40);

        customerC.setEditable(true);
        customerC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCActionPerformed(evt);
            }
        });
        getContentPane().add(customerC);
        customerC.setBounds(240, 110, 300, 40);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("DATE OF TRANASACTION");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 300, 150, 40);

        dateOfTransactionTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(dateOfTransactionTF);
        dateOfTransactionTF.setBounds(240, 310, 300, 40);

        doneB.setText("DONE");
        doneB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneBMouseClicked(evt);
            }
        });
        getContentPane().add(doneB);
        doneB.setBounds(370, 520, 130, 50);

        backB.setText("BACK");
        backB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBMouseClicked(evt);
            }
        });
        getContentPane().add(backB);
        backB.setBounds(670, 530, 110, 40);

        amountTypeTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(amountTypeTF);
        amountTypeTF.setBounds(240, 390, 300, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("AMOUNT TYPE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(130, 390, 100, 40);

        amountTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(amountTF);
        amountTF.setBounds(240, 240, 300, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("AMOUNT ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 230, 80, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCActionPerformed
        getAccount();
    }//GEN-LAST:event_customerCActionPerformed

    private void doneBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneBMouseClicked
        addRecord();

        transactionType obj= new transactionType();
        obj.setVisible(true);
        dispose();

    }//GEN-LAST:event_doneBMouseClicked

    private void backBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBMouseClicked
        transactionType obj= new transactionType();
        obj.setVisible(true);
        dispose();
    }//GEN-LAST:event_backBMouseClicked
    
    private void addRecord(){
    transactionBean bean = new      transactionBean();
    accountBean bean1 = (accountBean)accountC.getSelectedItem();
    if(bean1==null)return;
    int tra = bean.getTransactionId();
    String transactionType ="DPOSIT"; 
    int  amount = Integer.parseInt(amountTF.getText());    
    String dateOfTransaction = dateOfTransactionTF.getText();
    String amountType = amountTypeTF.getText();
    try{
        int row = databaseManager.addTransactionD(tra,bean1.getAccountNo(), amount,  amountType, dateOfTransaction,transactionType);
        if(row>=1)
            JOptionPane.showMessageDialog(this,"DPOSIT DONE ");
               
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,"erorr"+e.getMessage());
        e.printStackTrace();}
    
    
}
        private void getCustomer(){
      
    try{
        Vector v=databaseManager.getCustomer();
       customerC.removeAllItems();
           for(int i=0; i<v.size();  i++ ){ 
        customerBean  bean =(customerBean)v.elementAt(i);
        customerC.addItem(bean);
    } 

    }catch(Exception e){
        e.printStackTrace ();
      JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
    
    }      
    }
    
      private void getAccount(){
            customerBean bean=(customerBean) customerC.getSelectedItem();
            if(bean==null) return;
            try{
                accountC.removeAllItems();
                 Vector v=databaseManager.getAccount(bean.getCutomerId());

            for(int i=0;i<v.size();i++){
                accountBean bean1=(accountBean)v.elementAt(i);
                accountC.addItem(bean1);

            }
        }//end try block
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Error : "+e.getMessage());
        }//end catch
        }
     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dpositFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dpositFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dpositFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dpositFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dpositFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountC;
    private javax.swing.JTextField amountTF;
    private javax.swing.JTextField amountTypeTF;
    private javax.swing.JButton backB;
    private javax.swing.JComboBox customerC;
    private javax.swing.JTextField dateOfTransactionTF;
    private javax.swing.JButton doneB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
