/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Database.databaseManager;
import beanClasses.accountBean;
import beanClasses.customerBean;
import beanClasses.loanBean;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class loanF extends javax.swing.JFrame {

    /**
     * Creates new form loanF
     */
    public loanF() {
        initComponents();
        getCustomer();
    }
    
    private void getCustomer(){
      
    try{
        Vector v=databaseManager.getCustomer();
       customerCom.removeAllItems();
           for(int i=0; i<v.size();  i++ ){ 
        customerBean  bean =(customerBean)v.elementAt(i);
        customerCom.addItem(bean);
    } 

    }catch(Exception e){
        e.printStackTrace ();
      JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
    
    }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        accountNoTF = new javax.swing.JTextField();
        loanIdTF = new javax.swing.JTextField();
        kisitLimitTF = new javax.swing.JTextField();
        monthLimitTF = new javax.swing.JTextField();
        percentageTF = new javax.swing.JTextField();
        profitTF = new javax.swing.JTextField();
        customerCom = new javax.swing.JComboBox();
        accountCom = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        loanIdList = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        amountTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        paymentDateTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("PROFIT");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(360, 220, 41, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("REMARKS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 480, 57, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("ACCOUNT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(118, 152, 56, 15);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CUSTOMER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(109, 80, 65, 15);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("LOAN ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(128, 239, 46, 15);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("ACCOUNT NO");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(98, 284, 76, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("MONTH LIMIT");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(99, 363, 75, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("KISIT LIMIT");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 360, 62, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("PERCENTAGE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 280, 76, 40);

        accountNoTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(accountNoTF);
        accountNoTF.setBounds(178, 284, 150, 40);

        loanIdTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(loanIdTF);
        loanIdTF.setBounds(178, 214, 110, 40);

        kisitLimitTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(kisitLimitTF);
        kisitLimitTF.setBounds(410, 360, 140, 40);

        monthLimitTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(monthLimitTF);
        monthLimitTF.setBounds(178, 363, 150, 40);

        percentageTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        percentageTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                percentageTFActionPerformed(evt);
            }
        });
        getContentPane().add(percentageTF);
        percentageTF.setBounds(410, 280, 140, 40);

        profitTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(profitTF);
        profitTF.setBounds(410, 220, 140, 40);

        customerCom.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComActionPerformed(evt);
            }
        });
        getContentPane().add(customerCom);
        customerCom.setBounds(178, 71, 370, 33);

        accountCom.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        accountCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountComActionPerformed(evt);
            }
        });
        getContentPane().add(accountCom);
        accountCom.setBounds(178, 147, 370, 38);

        remarksTA.setColumns(20);
        remarksTA.setRows(5);
        jScrollPane1.setViewportView(remarksTA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 480, 570, 96);

        loanIdList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        loanIdList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                loanIdListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(loanIdList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(560, 70, 190, 390);

        jLabel10.setText("LOAN ID LIST");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(570, 50, 65, 14);

        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel11.setText("LOAN ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(307, 11, 127, 18);

        amountTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(amountTF);
        amountTF.setBounds(180, 420, 150, 40);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("amount");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(120, 420, 47, 40);

        paymentDateTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(paymentDateTF);
        paymentDateTF.setBounds(410, 420, 140, 40);

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("payment date");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(330, 420, 80, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loanIdListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_loanIdListValueChanged
 
     loanBean bean=(loanBean)loanIdList.getSelectedValue();
        if(bean==null)return;
        
        loanIdTF.setText(""+bean.getLoanId());
        accountNoTF.setText(""+bean.getAccountNo());
        amountTF.setText(""+bean.getAmount());
        monthLimitTF.setText(bean.getMonthLimit());
        kisitLimitTF.setText(""+bean.getKisitLimit());
        percentageTF.setText(""+bean.getPercentage());
        profitTF.setText(""+bean.getProfit());
        paymentDateTF.setText(bean.getPaymentDate());
        remarksTA.setText(bean.getRemarks());
   
        
        
    }//GEN-LAST:event_loanIdListValueChanged

    private void accountComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountComActionPerformed
        getLoan();
    }//GEN-LAST:event_accountComActionPerformed
private void getLoan(){
            accountBean bean = (accountBean)accountCom.getSelectedItem();
           if(bean==null)return;
           try{
               Vector v = databaseManager.getLoan(bean.getAccountId());
               loanIdList.setListData(v);
           }catch(Exception e){
              e.printStackTrace();
              JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
           }
           
       }
      
    
    private void customerComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComActionPerformed
        // TODO add your handling code here:
        getAccount();
    }//GEN-LAST:event_customerComActionPerformed

    private void percentageTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_percentageTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_percentageTFActionPerformed
    
    private void getAccount(){
            customerBean bean=(customerBean) customerCom.getSelectedItem();
            if(bean==null) return;
            try{
                accountCom.removeAllItems();
                 Vector v=databaseManager.getAccount(bean.getCutomerId());

            for(int i=0;i<v.size();i++){
                accountBean bean1=(accountBean)v.elementAt(i);
                accountCom.addItem(bean1);

            }
        }//end try block
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Error : "+e.getMessage());
        }//end catch
  
  }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loanF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loanF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loanF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loanF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loanF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountCom;
    private javax.swing.JTextField accountNoTF;
    private javax.swing.JTextField amountTF;
    private javax.swing.JComboBox customerCom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kisitLimitTF;
    private javax.swing.JList loanIdList;
    private javax.swing.JTextField loanIdTF;
    private javax.swing.JTextField monthLimitTF;
    private javax.swing.JTextField paymentDateTF;
    private javax.swing.JTextField percentageTF;
    private javax.swing.JTextField profitTF;
    private javax.swing.JTextArea remarksTA;
    // End of variables declaration//GEN-END:variables
}
