/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Database.databaseManager;
import beanClasses.accountBean;
import beanClasses.customerBean;
import beanClasses.loanBean;
import beanClasses.loanpaymentBean;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class loanPaymentFrame extends javax.swing.JFrame {

    /**
     * Creates new form loanPaymentFrame
     */
    public loanPaymentFrame() {
        initComponents();
        getCustomer();
    }
    private void getCustomer(){
      
    try{
        Vector v=databaseManager.getCustomer();
       customerCom.removeAllItems();
           for(int i=0; i<v.size();  i++ ){ 
        customerBean  bean =(customerBean)v.elementAt(i);
        customerCom.addItem(bean);
    } 

    }catch(Exception e){
        e.printStackTrace ();
      JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
    
    }      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        paymentAmountTF = new javax.swing.JTextField();
        loanpaymentIdTF = new javax.swing.JTextField();
        remmenderTF = new javax.swing.JTextField();
        totalPayTF = new javax.swing.JTextField();
        lateFeesTF = new javax.swing.JTextField();
        paymentDateTF = new javax.swing.JTextField();
        customerCom = new javax.swing.JComboBox();
        accountCom = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        loanpaymentIdList = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        loanIdCom = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("PAYMENT DATE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(321, 220, 90, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("REMARKS");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 430, 57, 15);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("ACCOUNT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(120, 130, 56, 30);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("CUSTOMER");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(110, 80, 65, 15);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("LOAN PAYMENT ID");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 220, 110, 40);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("PAYMENT AMOUNT");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(64, 284, 110, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("TOTAL PAY");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(99, 363, 64, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("REMANING");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 360, 90, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("LATE FEES");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 280, 60, 40);

        paymentAmountTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(paymentAmountTF);
        paymentAmountTF.setBounds(178, 284, 150, 40);

        loanpaymentIdTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(loanpaymentIdTF);
        loanpaymentIdTF.setBounds(180, 220, 110, 40);

        remmenderTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(remmenderTF);
        remmenderTF.setBounds(410, 360, 140, 40);

        totalPayTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(totalPayTF);
        totalPayTF.setBounds(178, 363, 150, 40);

        lateFeesTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lateFeesTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lateFeesTFActionPerformed(evt);
            }
        });
        getContentPane().add(lateFeesTF);
        lateFeesTF.setBounds(410, 280, 140, 40);

        paymentDateTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(paymentDateTF);
        paymentDateTF.setBounds(410, 220, 140, 40);

        customerCom.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComActionPerformed(evt);
            }
        });
        getContentPane().add(customerCom);
        customerCom.setBounds(180, 70, 370, 33);

        accountCom.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        accountCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountComActionPerformed(evt);
            }
        });
        getContentPane().add(accountCom);
        accountCom.setBounds(180, 120, 370, 38);

        remarksTA.setColumns(20);
        remarksTA.setRows(5);
        jScrollPane1.setViewportView(remarksTA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(180, 430, 570, 96);

        loanpaymentIdList.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        loanpaymentIdList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                loanpaymentIdListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(loanpaymentIdList);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(560, 70, 190, 330);

        jLabel10.setText("LOAN PAYMENT");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(300, 20, 120, 20);

        loanIdCom.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        loanIdCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanIdComActionPerformed(evt);
            }
        });
        getContentPane().add(loanIdCom);
        loanIdCom.setBounds(180, 170, 370, 38);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("LOAN");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(120, 170, 32, 40);

        jLabel12.setText("LOAN PAYMENT LIST");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(560, 50, 120, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lateFeesTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lateFeesTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lateFeesTFActionPerformed

    private void customerComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComActionPerformed
        // TODO add your handling code here:
        getAccount();
    }//GEN-LAST:event_customerComActionPerformed

    private void getAccount(){
            customerBean bean=(customerBean) customerCom.getSelectedItem();
            if(bean==null) return;
            try{
                accountCom.removeAllItems();
                 Vector v=databaseManager.getAccount(bean.getCutomerId());

            for(int i=0;i<v.size();i++){
                accountBean bean1=(accountBean)v.elementAt(i);
                accountCom.addItem(bean1);

            }
        }//end try block
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Error : "+e.getMessage());
        }//end catch
  
  }

    
    private void accountComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountComActionPerformed
        getLoan();
    }//GEN-LAST:event_accountComActionPerformed

     private void getLoan(){
            accountBean bean=(accountBean) accountCom.getSelectedItem();
            if(bean==null) return;
            try{
                loanIdCom.removeAllItems();
                 Vector v=databaseManager.getAccount(bean.getAccountId());

            for(int i=0;i<v.size();i++){
                loanBean bean1=(loanBean)v.elementAt(i);
                loanIdCom.addItem(bean1);

            }
        }//end try block
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Error : "+e.getMessage());
        }//end catch
  
  }

    
    private void loanpaymentIdListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_loanpaymentIdListValueChanged

        loanpaymentBean bean=(loanpaymentBean)loanpaymentIdList.getSelectedValue();
        if(bean==null)return;

        loanpaymentIdTF.setText(""+bean.getLoanId());
     
        paymentAmountTF.setText(""+bean.getPaymentAmount());
        paymentDateTF.setText(""+bean.getPaymentDate());
        lateFeesTF.setText(""+bean.getLateFees());
        remmenderTF.setText(""+bean.getRemender());
        totalPayTF.setText(""+bean.getTotalPay());
        remarksTA.setText(bean.getRemarks());

    }//GEN-LAST:event_loanpaymentIdListValueChanged

    private void loanIdComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanIdComActionPerformed
        getPaymentLoan();
    }//GEN-LAST:event_loanIdComActionPerformed
private void getPaymentLoan(){
            loanBean bean = (loanBean)loanIdCom.getSelectedItem();
           if(bean==null)return;
           try{
               Vector v = databaseManager.getLoan(bean.getLoanId());
               loanpaymentIdList.setListData(v);
           }catch(Exception e){
              e.printStackTrace();
              JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
           }
           
       }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loanPaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loanPaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loanPaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loanPaymentFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loanPaymentFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountCom;
    private javax.swing.JComboBox customerCom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lateFeesTF;
    private javax.swing.JComboBox loanIdCom;
    private javax.swing.JList loanpaymentIdList;
    private javax.swing.JTextField loanpaymentIdTF;
    private javax.swing.JTextField paymentAmountTF;
    private javax.swing.JTextField paymentDateTF;
    private javax.swing.JTextArea remarksTA;
    private javax.swing.JTextField remmenderTF;
    private javax.swing.JTextField totalPayTF;
    // End of variables declaration//GEN-END:variables
}
