/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Database.databaseManager;
import beanClasses.accountBean;
import beanClasses.customerBean;
import beanClasses.transactionBean;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class transaction extends javax.swing.JFrame {

    /**
     * Creates new form transaction
     */
    public transaction() {
        initComponents();
        getCustomer();
    }
    
    private void deleteRecord(){
    transactionBean bean = (transactionBean)transactionL.getSelectedValue();
    if(bean==null)return ; {
    try{
        int rows = databaseManager.deleteTransaction(bean.getTransactionId());
         if(rows>=1)
             JOptionPane.showMessageDialog(this,rows+"delete");
            getTransaction();
    }catch (Exception e){
        JOptionPane.showMessageDialog(this,"error"+e.getMessage());
        e.printStackTrace();}
    }
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        accountC = new javax.swing.JComboBox();
        transactionIdTF = new javax.swing.JTextField();
        amountTF = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        remarksA = new javax.swing.JTextArea();
        backB = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        transactionL = new javax.swing.JList();
        customerC = new javax.swing.JComboBox();
        amountTypeC = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        dateTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        transactionTypeTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        balanceTF1 = new javax.swing.JTextField();
        chequeTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        totalAmountTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TRANSACTION");
        setMinimumSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("TRANSACTION ID");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 220, 100, 40);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("ACCOUNT ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 160, 90, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("CUSTOMER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 110, 90, 40);

        accountC.setEditable(true);
        accountC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        accountC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountCActionPerformed(evt);
            }
        });
        getContentPane().add(accountC);
        accountC.setBounds(220, 160, 300, 40);

        transactionIdTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(transactionIdTF);
        transactionIdTF.setBounds(220, 270, 150, 40);

        amountTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(amountTF);
        amountTF.setBounds(220, 360, 150, 40);

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("AMOUNT TYPE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(220, 410, 100, 50);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("REMARKS");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(150, 510, 60, 15);

        remarksA.setColumns(20);
        remarksA.setRows(5);
        jScrollPane1.setViewportView(remarksA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 510, 620, 90);

        backB.setBackground(new java.awt.Color(255, 255, 255));
        backB.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        backB.setForeground(new java.awt.Color(255, 0, 0));
        backB.setText("BACK");
        backB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBMouseClicked(evt);
            }
        });
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        getContentPane().add(backB);
        backB.setBounds(740, 610, 90, 40);

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("TRANSACTION LIST");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(610, 80, 110, 20);

        transactionL.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        transactionL.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                transactionLValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(transactionL);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(550, 110, 290, 290);

        customerC.setEditable(true);
        customerC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCActionPerformed(evt);
            }
        });
        getContentPane().add(customerC);
        customerC.setBounds(220, 110, 300, 40);

        amountTypeC.setEditable(true);
        amountTypeC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(amountTypeC);
        amountTypeC.setBounds(220, 460, 120, 40);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("NEW TRANSACTIOM");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 610, 300, 40);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("AMOUNT");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(220, 310, 90, 40);
        getContentPane().add(dateTF);
        dateTF.setBounds(700, 460, 140, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("DATE");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(700, 420, 90, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("TRANSACTION TYPE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 310, 120, 50);

        transactionTypeTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(transactionTypeTF);
        transactionTypeTF.setBounds(390, 360, 140, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("BALANCE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(390, 220, 90, 40);
        getContentPane().add(balanceTF1);
        balanceTF1.setBounds(390, 270, 140, 40);
        getContentPane().add(chequeTF);
        chequeTF.setBounds(530, 460, 130, 40);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("CHEQUE NO");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(530, 420, 70, 40);

        totalAmountTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(totalAmountTF);
        totalAmountTF.setBounds(390, 460, 120, 40);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("TOTAL AMOUNT");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(390, 420, 100, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        hide();
    }//GEN-LAST:event_backBActionPerformed

    private void transactionLValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_transactionLValueChanged
    transactionBean bean=(transactionBean)transactionL.getSelectedValue();
        if(bean==null)return;
        
        transactionIdTF.setText(""+bean.getTransactionId());
        amountTF.setText(""+bean.getAmount());
        chequeTF.setText(""+bean.getCheque());
        amountTypeC.setSelectedItem(bean.getAmountType());
        transactionTypeTF.setText(bean.getTransactionType());
        remarksA.setText(bean.getRemarks());
        //totalAmountTF.setText(bean.);
        dateTF.setText(""+bean.getdateOfTransaction());
        balanceTF1.setText(""+bean.getBalance());
    }//GEN-LAST:event_transactionLValueChanged

    private void customerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCActionPerformed
        getAccount();
    }//GEN-LAST:event_customerCActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
      transactionType ob = new transactionType();
      ob.setVisible(true);
      dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void backBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBMouseClicked
    Bank ob = new Bank();
    ob.setVisible(true);
    dispose();
    }//GEN-LAST:event_backBMouseClicked

    private void accountCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountCActionPerformed
        getTransaction();
    }//GEN-LAST:event_accountCActionPerformed

    private void getCustomer(){
      
    try{
        Vector v=databaseManager.getCustomer();
       customerC.removeAllItems();
           for(int i=0; i<v.size();  i++ ){ 
        customerBean  bean =(customerBean)v.elementAt(i);
        customerC.addItem(bean);
    } 

    }catch(Exception e){
        e.printStackTrace ();
      JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
    
    }      
    }
    
      private void getAccount(){
            customerBean bean=(customerBean) customerC.getSelectedItem();
            if(bean==null) return;
            try{
                accountC.removeAllItems();
                 Vector v=databaseManager.getAccount(bean.getCutomerId());

            for(int i=0;i<v.size();i++){
                accountBean bean1=(accountBean)v.elementAt(i);
                accountC.addItem(bean1);

            }
        }//end try block
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Error : "+e.getMessage());
        }//end catch
        }

      private void getTransaction(){
            accountBean bean = (accountBean)accountC.getSelectedItem();
           if(bean==null)return;
           try{
               Vector v = databaseManager.getTransaction(bean.getAccountNo());
               transactionL.setListData(v);
           }catch(Exception e){
              e.printStackTrace();
              JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
           }
           
       }
      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaction.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaction().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountC;
    private javax.swing.JTextField amountTF;
    private javax.swing.JComboBox amountTypeC;
    private javax.swing.JButton backB;
    private javax.swing.JTextField balanceTF1;
    private javax.swing.JTextField chequeTF;
    private javax.swing.JComboBox customerC;
    private javax.swing.JTextField dateTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea remarksA;
    private javax.swing.JTextField totalAmountTF;
    private javax.swing.JTextField transactionIdTF;
    private javax.swing.JList transactionL;
    private javax.swing.JTextField transactionTypeTF;
    // End of variables declaration//GEN-END:variables
}
