/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import Database.databaseManager;
import beanClasses.accountBean;
import beanClasses.customerBean;
import beanClasses.transactionBean;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class withdraw extends javax.swing.JFrame {

    /**
     * Creates new form withdraw
     */
    public withdraw() {
        initComponents();
        getCustomer();
    }
    
 
    private void clear(){
    
    chequeTF.setText("");
    amountTF.setText("");    
    dateOfTransactionTF.setText("");
    amountTypeTF.setText("");
    
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountTF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        dateOfTransactionTF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        amountTypeTF = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        chequeTF = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        accountC = new javax.swing.JComboBox();
        customerC = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(755, 450));
        getContentPane().setLayout(null);

        amountTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(amountTF);
        amountTF.setBounds(270, 240, 300, 40);

        jLabel2.setText("WITH DROW");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(310, 10, 70, 30);

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("DATE OF TRANASACTION");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(100, 290, 150, 40);

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("WITHDRAW");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(320, 520, 200, 40);

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("BACK");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(610, 520, 90, 40);

        dateOfTransactionTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(dateOfTransactionTF);
        dateOfTransactionTF.setBounds(270, 290, 300, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("AMOUNT");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 240, 70, 40);

        amountTypeTF.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(amountTypeTF);
        amountTypeTF.setBounds(270, 340, 300, 40);

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("AMOUNT TYPE");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 340, 100, 40);
        getContentPane().add(chequeTF);
        chequeTF.setBounds(270, 390, 300, 40);

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("CHEQUE NO");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(160, 390, 70, 40);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("ACCOUNT ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 180, 90, 40);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("CUSTOMER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 120, 90, 40);

        accountC.setEditable(true);
        accountC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(accountC);
        accountC.setBounds(270, 180, 300, 40);

        customerC.setEditable(true);
        customerC.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        customerC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerCActionPerformed(evt);
            }
        });
        getContentPane().add(customerC);
        customerC.setBounds(270, 120, 300, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        addRecord();
        clear();
       transactionType obj= new transactionType();
       obj.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
         transactionType obj= new transactionType();
       obj.setVisible(true);
       dispose();
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void customerCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerCActionPerformed
        getAccount();
    }//GEN-LAST:event_customerCActionPerformed


     private void addRecord(){
    transactionBean bean = new      transactionBean();
     accountBean bean1 = (accountBean)accountC.getSelectedItem();
    int tra = bean.getTransactionId();

    int accountNo = bean1.getAccountNo();
    int cheque = Integer.parseInt(chequeTF.getText());
    String transactionType = "TRANSFER ";
    int  amount = Integer.parseInt(amountTF.getText());    
    String dateOfTransaction = dateOfTransactionTF.getText();
    String amountType = amountTypeTF.getText();
    
    try{
        int row = databaseManager.addTransactionW(tra,accountNo, amount,  amountType, dateOfTransaction,transactionType,cheque);
        if(row>=1)
                JOptionPane.showMessageDialog(this," WITHDRAW DONE ");
                //clear();
            //    getTransaction();
    }catch(Exception e){
        JOptionPane.showMessageDialog(this,"erorr"+e.getMessage());
        e.printStackTrace();}
    
    
}
   
         private void getCustomer(){
      
    try{
        Vector v=databaseManager.getCustomer();
       customerC.removeAllItems();
           for(int i=0; i<v.size();  i++ ){ 
        customerBean  bean =(customerBean)v.elementAt(i);
        customerC.addItem(bean);
    } 

    }catch(Exception e){
        e.printStackTrace ();
      JOptionPane.showMessageDialog(this,"Error"+e.getMessage());
    
    }      
    }
    
      private void getAccount(){
            customerBean bean=(customerBean) customerC.getSelectedItem();
            if(bean==null) return;
            try{
                accountC.removeAllItems();
                 Vector v=databaseManager.getAccount(bean.getCutomerId());

            for(int i=0;i<v.size();i++){
                accountBean bean1=(accountBean)v.elementAt(i);
                accountC.addItem(bean1);

            }
        }//end try block
        catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Error : "+e.getMessage());
        }//end catch
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new withdraw().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox accountC;
    private javax.swing.JTextField amountTF;
    private javax.swing.JTextField amountTypeTF;
    private javax.swing.JTextField chequeTF;
    private javax.swing.JComboBox customerC;
    private javax.swing.JTextField dateOfTransactionTF;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables


}
